## This provides the generators provided by Nixpkgs with two changes:
##
## 1. when possible, it adds a “generated by Project Manager” comment and
## 2. when necessary, it adds a trailing newline, to make it a valid POSIX file.
{lib}: let
  message = "This file was generated by Project Manager.";
in {
  toDhall = args: v:
    ''
      --| ${message}
    ''
    + lib.generators.toDhall args v;
  toGitINI = v:
    ''
      ; ${message}
    ''
    + lib.generators.toGitINI v;
  toINI = args: v:
    ''
      ; ${message}
    ''
    + lib.generators.toINI args v;
  toINIWithGlobalSection = args: v:
    ''
      ; ${message}
    ''
    + lib.generators.toINIWithGlobalSection args v;
  ## NB: JSON doesn't support comments, but we re-export `toJSON` here for
  ##     consistency.
  toJSON = args: v: lib.generators.toJSON args v + "\n";
  toLua = {indent, ...} @ args: v:
    ''
      ${indent}-- ${message}
    ''
    + lib.generators.toLua args v;
  toPlist = args: v:
    ''
      <!-- ${message} -->
    ''
    + lib.generators.toPlist args v;
  toPretty = args: v:
    ''
      # ${message}
    ''
    + lib.generators.toPretty args v
    + "\n";
  toTOML = args: v:
    ''
      # ${message}
    ''
    + lib.generators.toINIWithGlobalSection args v;
  toYAML = options: v:
    ''
      # ${message}
    ''
    + lib.generators.toYAML options v
    + "\n";
}
