{lib}: let
  message = "This file was generated by Project Manager.";
in {
  toDhall = args: v:
    ''
      --| ${message}
    ''
    + lib.generators.toDhall args v;
  toGitINI = v:
    ''
      ; ${message}
    ''
    + lib.generators.toGitINI v;
  toINI = args: v:
    ''
      ; ${message}
    ''
    + lib.generators.toINI args v;
  toINIWithGlobalSection = args: v:
    ''
      ; ${message}
    ''
    + lib.generators.toINIWithGlobalSection args v;
  ## NB: JSON doesn't support comments, but we re-export `toJSON` here for
  ##     consistency.
  toJSON = lib.generators.toJSON;
  toLua = {indent, ...} @ args: v:
    ''
      ${indent}-- ${message}
    ''
    + lib.generators.toLua args v;
  toPlist = args: v:
    ''
      <!-- ${message} -->
    ''
    + lib.generators.toPlist args v;
  toTOML = args: v:
    ''
      # ${message}
    ''
    + lib.generators.toINIWithGlobalSection args v;
  toYAML = options: v:
    ''
      # ${message}
    ''
    + lib.generators.toYAML options v;
}
