[[sec-release-23.11]]
== Release 23.11

This is the current unstable branch and the information in this section is therefore not final.

[[sec-release-23.11-highlights]]
=== Highlights
:babelfish: https://github.com/bouk/babelfish
:nixpkgs-markdown: https://nixos.org/manual/nixpkgs/unstable/#sec-contributing-markup

This release has the following notable changes:

* The `.release` file in the Home Manager source tree
has been supplanted by `release.json`,
which contains more information about the branch.
If you have any external code reading this file,
please switch to consuming `release.json` instead.
The `.release` file will be removed in 24.05.

* Home Manager has migrated to using
the upstream Nixpkgs `lib.nixosOptionsDoc` processor
for option documentation.
If you have any external Home Manager modules,
their option descriptions and literal examples should be translated
to {nixpkgs-markdown}[Nixpkgs-flavoured Markdown].

[[sec-release-23.11-state-version-changes]]
=== State Version Changes

The state version in this release includes the changes below.
These changes are only active if the `home.stateVersion` option is set to "23.11" or later.

* Nothing, yet.
