[[ch-faq]]
== Frequently Asked Questions (FAQ)

=== Why are the session variables not set?
:foreign-env: https://github.com/oh-my-fish/plugin-foreign-env

Project Manager is only able to set session variables automatically in derivations that extend the ones provided by Project Manager.

=== How do I install packages from Nixpkgs unstable?

If you are using a stable version of Nixpkgs but would like to install some particular packages from Nixpkgs unstable – or some other channel – then you can import the unstable Nixpkgs and refer to its packages within your configuration. Something like

[source,nix]
----
{ pkgs, config, ... }:

let

  pkgsUnstable = import <nixpkgs-unstable> {};

in

{
  project.devPackages = [
    pkgsUnstable.foo
  ];

  # …
}
----

should work provided you have a Nix channel called `nixpkgs-unstable`.

You can add the `nixpkgs-unstable` channel by running

[source,console]
----
$ nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs-unstable
$ nix-channel --update
----

Note, the package won’t be affected by any package overrides, overlays, etc.

=== How do I override the package used by a module?
:nixpkgs-overlays: https://nixos.org/nixpkgs/manual/#chap-overlays

By default Project Manager will install the package provided by your chosen `nixpkgs` channel but occasionally you might end up needing to change this package. This can typically be done in two ways.

1. If the module provides a `package` option, such as `programs.beets.package`, then this is the recommended way to perform the override. For example,
+
[source,nix]
programs.beets.package = pkgs.beets.override { enableCheck = true; };

2. If no `package` option is available then you can typically override the relevant package using an {nixpkgs-overlays}[overlay].
+
For example, if you want to use the `programs.skim` module but use the `skim` package from Nixpkgs unstable, then a configuration like
+
[source,nix]
----
{ pkgs, config, ... }:

let

  pkgsUnstable = import <nixpkgs-unstable> {};

in

{
  programs.skim.enable = true;

  nixpkgs.overlays = [
    (self: super: {
      skim = pkgsUnstable.skim;
    })
  ];

  # …
}
----
+
should work OK.
