[[ch-installation]]
== Installing Project Manager

:nixos-wiki-flakes: https://nixos.wiki/wiki/Flakes

Project Manager can be used in three primary ways:

1. Using the standalone `project-manager` tool.

[NOTE]
In this chapter we describe how to install Project Manager in the
standard way using channels. If you prefer to use
{nixos-wiki-flakes}[Nix Flakes] then please see the instructions in
<<ch-nix-flakes>>.

[[sec-install-standalone]]
=== Standalone installation

:nix-allowed-users: https://nixos.org/nix/manual/#conf-allowed-users
:nixos-allowed-users: https://nixos.org/manual/nixos/stable/options.html#opt-nix.settings.allowed-users
:bash: https://www.gnu.org/software/bash/
:zsh: http://zsh.sourceforge.net/
:fish: https://fishshell.com
:plugin-foreign-env: https://github.com/oh-my-fish/plugin-foreign-env
:babelfish: https://github.com/bouk/babelfish

1. Make sure you have a working Nix installation. Specifically, make
sure that your user is able to build and install Nix packages. For
example, you should be able to successfully run a command like
`nix-instantiate '<nixpkgs>' -A hello` without having to switch to the
root user. For a multi-user install of Nix this means that your user
must be covered by the {nix-allowed-users}[`allowed-users`] Nix
option. On NixOS you can control this option using the
{nixos-allowed-users}[`nix.settings.allowed-users`] system option.

2. Add the appropriate Project Manager channel. If you are following
Nixpkgs master or an unstable channel you can run
+
[source,console]
----
$ nix-channel --add https://github.com/sellout/project-manager/archive/master.tar.gz project-manager
$ nix-channel --update
----
+
and if you follow a Nixpkgs version 23.05 channel you can run
+
[source,console]
----
$ nix-channel --add https://github.com/sellout/project-manager/archive/release-23.05.tar.gz project-manager
$ nix-channel --update
----

3. Run the Project Manager installation command and create the first Project
Manager generation:
+
[source,console]
$ nix-shell '<project-manager>' -A install
+
Once finished, Project Manager should be active and available in your
user environment.

4. If you do not plan on having Project Manager manage your shell
configuration then you must source the
+
[source,bash]
$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh
+
file in your shell configuration. Alternatively source
+
[source,bash]
/etc/profiles/per-user/$USER/etc/profile.d/hm-session-vars.sh
+
when managing home configuration together with system configuration.
+
This file can be sourced directly by POSIX.2-like shells such as
{bash}[Bash] or {zsh}[Z shell]. {fish}[Fish] users can use utilities
such as {plugin-foreign-env}[foreign-env] or {babelfish}[babelfish].
+
For example, if you use Bash then add
+
[source,bash]
----
. "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh"
----
+
to your `~/.profile` file.

Once installed you can see <<ch-usage>> for a more detailed
description of Project Manager and how to use it.
