[[ch-usage]]
== Using Project Manager

Your use of Project Manager is centered around the configuration file,
which is typically found at `$PROJECT_ROOT/.config/project.nix` in the standard installation
or `$PROJECT_ROOT/flake.nix` in a Nix flake based installation.

[NOTE]
The default configuration used to be placed in `~/.config/nixpkgs`¸
so you may see references to that elsewhere.
The old directory still works but Project Manager will print a warning message when used.

This configuration file can be _built_ and _activated_.

Building a configuration produces a directory in the Nix store that contains all files and programs that should be available in your project directory and Nix user profile, respectively. The build step also checks that the configuration is valid and it will fail with an error if you, for example, assign a value to an option that does not exist or assign a value of the wrong type. Some modules also have custom assertions that perform more detailed, module specific, checks.

Concretely, if your configuration contains

[source,nix]
programs.git.enable = "yes";

then building it, for example using `project-manager build`, will result in an error message saying something like

[source,console]
----
$ project-manager build
error: A definition for option `programs.git.enable' is not of type `boolean'. Definition values:
- In `/.../.config/project.nix': "yes"
(use '--show-trace' to show detailed location information)
----

The message indicates that you must provide a Boolean value for this option, that is, either `true` or `false`. The documentation of each option will state the expected type, for <<opt-programs.git.enable>> you will see ``Type: boolean''. You there also find information about the default value and a description of the option. You can find the complete option documentation in <<ch-options>> or directly in the terminal by running

[source,console]
man project-configuration.nix

Once a configuration is successfully built, it can be activated. The activation performs the steps necessary to make the files, programs, and services available in your user environment. The `project-manager switch` command performs a combined build and activation.

[[sec-usage-configuration]]
=== Configuration Example

A fresh install of Project Manager will generate a minimal `$PROJECT_ROOT/.config/project.nix` file containing something like

[source,nix]
----
{ config, pkgs, ... }:

{
  # This value determines the Project Manager release that your
  # configuration is compatible with. This helps avoid breakage
  # when a new Project Manager release introduces backwards
  # incompatible changes.
  #
  # You can update Project Manager without changing this value. See
  # the Project Manager release notes for a list of state version
  # changes in each release.
  project.stateVersion = 0;

  # Let Project Manager install and manage itself.
  programs.project-manager.enable = true;
}
----

You can use this as a base for your further configurations.

[NOTE]
If you are not very familiar with the Nix language and NixOS modules then it is encouraged to start with small and simple changes. As you learn you can gradually grow the configuration with confidence.

As an example, let us expand the initial configuration file to also install the htop and fortune packages, install Emacs with a few extra packages available, and enable the user gpg-agent service.

To satisfy the above setup we should elaborate the `project.nix` file as follows:

[source,nix]
----
{ config, pkgs, ... }:

{
  # Packages that should be installed to the project profile.
  project.packages = [                               <1>
    pkgs.htop
    pkgs.fortune
  ];

  # This value determines the Project Manager release that your
  # configuration is compatible with. This helps avoid breakage
  # when a new Project Manager release introduces backwards
  # incompatible changes.
  #
  # You can update Project Manager without changing this value. See
  # the Project Manager release notes for a list of state version
  # changes in each release.
  project.stateVersion = 0;

  # Let Project Manager install and manage itself.
  programs.project-manager.enable = true;

  programs.emacs = {                              <2>
    enable = true;
    extraPackages = epkgs: [
      epkgs.nix-mode
      epkgs.magit
    ];
  };

  services.gpg-agent = {                          <3>
    enable = true;
    defaultCacheTtl = 1800;
    enableSshSupport = true;
  };
}
----
<1> Nixpkgs packages can be installed to the dev shell using <<opt-project.packages>>.
<2> The option names of a program module typically start with `programs.<package name>`.
<3> Similarly, for a service module, the names start with `services.<package name>`. Note in some cases a package has both programs _and_ service options – Emacs is such an example.

To activate this configuration you can run

[source,console]
project-manager switch

or if you are not feeling so lucky,

[source,console]
project-manager build

which will create a `result` link to a directory containing an
activation script and the generated project directory files.

[[sec-usage-rollbacks]]
=== Rollbacks

While the `project-manager` tool does not explicitly support rollbacks at the moment it is relatively easy to perform one manually. The steps to do so are

1.  Run `project-manager generations` to determine which generation you wish to rollback to:
+
[source,console]
----
$ project-manager generations
2018-01-04 11:56 : id 765 -> /nix/store/kahm1rxk77mnvd2l8pfvd4jkkffk5ijk-project-manager-generation
2018-01-03 10:29 : id 764 -> /nix/store/2wsmsliqr5yynqkdyjzb1y57pr5q2lsj-project-manager-generation
2018-01-01 12:21 : id 763 -> /nix/store/mv960kl9chn2lal5q8lnqdp1ygxngcd1-project-manager-generation
2017-12-29 21:03 : id 762 -> /nix/store/6c0k1r03fxckql4vgqcn9ccb616ynb94-project-manager-generation
2017-12-25 18:51 : id 761 -> /nix/store/czc5y6vi1rvnkfv83cs3rn84jarcgsgh-project-manager-generation
…
----

2.  Copy the Nix store path of the generation you chose, e.g.,
+
----
/nix/store/mv960kl9chn2lal5q8lnqdp1ygxngcd1-project-manager-generation
----
+
for generation 763.

3.  Run the `activate` script inside the copied store path:
+
[source,console]
----
$ /nix/store/mv960kl9chn2lal5q8lnqdp1ygxngcd1-project-manager-generation/activate
Starting project manager activation
…
----
