#!/usr/bin/env bash

# Prepare to use tools from Nixpkgs.
PATH=@DEP_PATH@${PATH:+:}$PATH

## See sellout/bash-strict-mode#10 for why we can’t use `strict-bash` directly.
# shellcheck disable=SC1091
source strict-mode.bash

export TEXTDOMAIN=project-manager
export TEXTDOMAINDIR=@OUT@/share/locale

# shellcheck disable=1091
source @PROJECT_MANAGER_LIB@

function showHelp() {
  echo "Usage: $0 [OPTION] COMMAND"
  echo
  echo "Options"
  echo
  echo "  -f FILE           The project configuration file."
  echo "                    Default is '\$PROJECT_ROOT/.config/project/default.nix'."
  echo "  -I PATH           Add a path to the Nix expression search path."
  echo "  -v                Verbose output"
  echo "  -n                Do a dry run, only prints what actions would be taken"
  echo "  -h                Print this help"
  echo "  --version         Print the Project Manager version"
  echo
  echo "Options passed on to nix-build(1)"
  echo
  echo "  --arg(str) NAME VALUE    Override inputs passed to project-manager.nix"
  echo "  --cores NUM"
  echo "  --debug"
  echo "  --impure"
  echo "  --keep-failed"
  echo "  --keep-going"
  echo "  -j, --max-jobs NUM"
  echo "  --option NAME VALUE"
  echo "  -L, --print-build-logs"
  echo "  --show-trace"
  echo "  --(no-)substitute"
  echo "  --no-out-link            Do not create a symlink to the output path"
  echo "  --no-write-lock-file"
  echo "  --builders VALUE"
  echo "  --refresh                Consider all previously downloaded files out-of-date"
  echo
  echo "Commands"
  echo
  echo "  help         Print this help"
  echo
  echo '  edit         Open the project configuration in $EDITOR'
  echo
  echo "  build        Build configuration into result directory"
  echo
  echo "  init [--switch] [DIR]"
  echo "      Initializes a configuration for a project in the given directory."
  echo "      If the directory does not exist, then it will be created. The"
  echo "      default directory is the directory the command is run from."
  echo
  echo "      --switch      Immediately activate the generated configuration."
  echo
  echo "  switch       Build and activate configuration"
  echo
  echo "  generations  List all project environment generations"
  echo
  echo "  remove-generations ID..."
  echo "      Remove indicated generations. Use 'generations' command to"
  echo "      find suitable generation numbers."
  echo
  echo "  expire-generations TIMESTAMP"
  echo "      Remove generations older than TIMESTAMP where TIMESTAMP is"
  echo "      interpreted as in the -d argument of the date tool. For"
  echo '      example "-30 days" or "2018-01-01".'
  echo
  echo "  packages     List all packages installed in project-manager-path"
  echo
  echo "  news         Show news entries in a pager"
  echo
  echo "  uninstall    Remove Project Manager"
}

EXTRA_NIX_PATH=()
PASSTHROUGH_OPTS=()
COMMAND=""
COMMAND_ARGS=()

while [[ $# -gt 0 ]]; do
  opt="$1"
  shift
  case $opt in
    build | init | edit | expire-generations | generations | help | news | packages | remove-generations | switch | uninstall)
      COMMAND="$opt"
      ;;
    -I)
      EXTRA_NIX_PATH+=("$1")
      shift
      ;;
    -f | --file)
      export PROJECT_MANAGER_CONFIG="$1"
      shift
      ;;
    --recreate-lock-file | --no-update-lock-file | --no-write-lock-file | --no-registries | --commit-lock-file | --refresh)
      PASSTHROUGH_OPTS+=("$opt")
      ;;
    --update-input)
      PASSTHROUGH_OPTS+=("$opt" "$1")
      shift
      ;;
    --override-input)
      PASSTHROUGH_OPTS+=("$opt" "$1" "$2")
      shift 2
      ;;
    --experimental-features)
      PASSTHROUGH_OPTS+=("$opt" "$1")
      shift
      ;;
    --extra-experimental-features)
      PASSTHROUGH_OPTS+=("$opt" "$1")
      shift
      ;;
    --no-out-link)
      export NO_OUT_LINK=1
      ;;
    -L | --print-build-logs)
      export PRINT_BUILD_LOGS=1
      ;;
    -h | --help)
      showHelp
      exit 0
      ;;
    -n | --dry-run)
      export DRY_RUN=1
      ;;
    --option | --arg | --argstr)
      PASSTHROUGH_OPTS+=("$opt" "$1" "$2")
      shift 2
      ;;
    -j | --max-jobs | --cores | --builders)
      PASSTHROUGH_OPTS+=("$opt" "$1")
      shift
      ;;
    --debug | --eval-cache | --no-eval-cache | --keep-failed | --keep-going | --show-trace | --substitute | --no-substitute | --impure)
      PASSTHROUGH_OPTS+=("$opt")
      ;;
    -v | --verbose)
      export VERBOSE=1
      ;;
    --version)
      echo @VERSION@
      exit 0
      ;;
    *)
      case $COMMAND in
        init | expire-generations | remove-generations | option)
          COMMAND_ARGS+=("$opt")
          ;;
        *)
          _iError "%s: unknown option '%s'" "$0" "$opt" >&2
          _i "Run '%s --help' for usage help" "$0" >&2
          exit 1
          ;;
      esac
      ;;
  esac
done

if [[ -z $COMMAND ]]; then
  showHelp >&2
  exit 1
fi

function pm_init() {
  # The directory where we should place the initial configuration.
  local projectDir

  # Whether we should immediate activate the configuration.
  local switch

  # Whether we should create a flake file.
  local withFlake

  if hasFlakeSupport; then
    withFlake=1
  fi

  while (($# > 0)); do
    local opt="$1"
    shift

    case $opt in
      --no-flake)
        unset withFlake
        ;;
      --switch)
        switch=1
        ;;
      -*)
        _iError "%s: unknown option '%s'" "$0" "$opt" >&2
        exit 1
        ;;
      *)
        if [[ -v projectDir ]]; then
          _i "Run '%s --help' for usage help" "$0" >&2
          exit 1
        else
          projectDir="$opt"
        fi
        ;;
    esac
  done

  PROJECT_ROOT="${projectDir:=$(pwd)}"
  export PROJECT_ROOT

  local confDir="${PROJECT_ROOT}/.config/project"

  if [[ ! -e $confDir ]]; then
    mkdir -p "$confDir"
  fi

  if [[ ! -d $confDir ]]; then
    _iError "%s: unknown option '%s'" "$0" "$opt" >&2
    exit 1
  fi

  local confFile="$confDir/default.nix"
  local flakeFile="${PROJECT_ROOT}/flake.nix"

  if [[ -e $confFile ]]; then
    _i 'The file %s already exists, leaving it unchanged...' "$confFile"
  else
    _i 'Creating %s...' "$confFile"

    mkdir -p "$confDir"
    cp '@CONFIG_TEMPLATE@' "$confFile"
  fi

  if [[ ! -v withFlake ]]; then
    PROJECT_MANAGER_CONFIG="$confFile"
  else
    if [[ -e $flakeFile ]]; then
      _i 'The file %s already exists, leaving it unchanged...' "$flakeFile"
    else
      _i 'Creating %s...' "$flakeFile"

      mkdir -p "$confDir"
      cp "@FLAKE_TEMPLATE@" "$flakeFile"
    fi
  fi

  if [[ -v switch ]]; then
    echo
    _i "Creating initial Project Manager generation..."
    echo

    if pm_switch; then
      # translators: The "%s" specifier will be replaced by a file path.
      _i $'All done! The project-manager tool should now be installed and you can edit\n\n    %s\n\nto configure Project Manager. Run \'man project-configuration.nix\' to\nsee all available options.' \
        "$confFile"
      exit 0
    else
      # translators: The "%s" specifier will be replaced by a URL.
      _i $'Uh oh, the installation failed! Please create an issue at\n\n    %s\n\nif the error seems to be the fault of Project Manager.' \
        "https://github.com/sellout/project-manager/issues"
      exit 1
    fi
  fi
}

case $COMMAND in
  edit)
    pm_edit
    ;;
  build)
    pm_build
    ;;
  init)
    pm_init "${COMMAND_ARGS[@]}"
    ;;
  switch)
    pm_switch
    ;;
  generations)
    pm_listGenerations
    ;;
  remove-generations)
    pm_removeGenerations "${COMMAND_ARGS[@]}"
    ;;
  expire-generations)
    if [[ ${#COMMAND_ARGS[@]} != 1 ]]; then
      _i 'expire-generations expects one argument, got %d.' "${#COMMAND_ARGS[@]}" >&2
      exit 1
    else
      pm_expireGenerations "${COMMAND_ARGS[@]}"
    fi
    ;;
  packages)
    pm_listPackages
    ;;
  news)
    pm_showNews --all
    ;;
  uninstall)
    pm_uninstall
    ;;
  help)
    showHelp
    ;;
  *)
    _iError 'Unknown command: %s' "$COMMAND" >&2
    showHelp >&2
    exit 1
    ;;
esac

# vim: ft=bash
